# https://taskfile.dev

version: '3'

silent: true

vars:
  ARTIFACT_REPO_FILES: https://raw.githubusercontent.com/bth-python/python-abcd25/refs/heads/main/
  ARTIFACT_TMP_FILES: /tmp/tmp-artifacts
  ARTIFACT_REPO: https://github.com/bth-python/python-abcd25

tasks:

  create-src-dirs:
    desc: "Creates the src directory structure if they do not exist"
    cmds:
      - mkdir -p src/kmom01/{convert,lab_01,practice,split_bill} src/kmom02/{marvin1,practice,practice_validation} src/kmom03/{marvin2,practice,practice_validation} src/kmom04/{marvin3,practice,practice_validation,lab_04} src/kmom05/{emissions,practice,practice_validation}
      - echo "Source directories created successfully. PS empty directories are not shown with 'git status'."
      - tree -d src

  download-artifacts:
    desc: "Downloads the artifacts repo to /tmp/tmp-artifacts"
    internal: true
    cmds:
      - task: clear-artifacts
      - git clone --quiet {{.ARTIFACT_REPO}}.git {{.ARTIFACT_TMP_FILES}}



  clear-artifacts:
    desc: "Removes /tmp/tmp-artifacts, used to clear the artifacts repo"
    internal: true
    cmds:
      - rm -rf {{.ARTIFACT_TMP_FILES}}



  download-tests:
    desc: "Replaces files in tests/ with files from the artifact repository, {{.ARTIFACT_REPO}}"
    cmds:
      - task: download-artifacts
      - cp -a {{.ARTIFACT_TMP_FILES}}/tests/. tests
      - task: clear-artifacts
      - echo "Tests downloaded successfully."



  download-ruff-config:
    desc: "Downloads the ruff configuration file from the artifact repository"
    cmds:
      - curl -s -L -o ruff.toml {{.ARTIFACT_REPO_FILES}}/ruff.toml
      - echo "Ruff configuration downloaded successfully."



  download-taskfile:
    desc: "Downloads the Taskfile from the artifact repository"
    cmds:
      - curl -s -L -o Taskfile.yml {{.ARTIFACT_REPO_FILES}}/Taskfile.yml
      - echo "Taskfile downloaded successfully."



  download-lab:
    desc: "Download a lab. Run with 'uv run task download-lab -- lab_XX', replace XX with the lab number."
    dir: "{{.USER_WORKING_DIR}}"
    preconditions:
      - sh: '[[ "$PWD" == */{{.CLI_ARGS}} ]]'
        msg: "You must stand in a directory called 'lab_XX' to run this task. EX. 'lab_01'."
    prompt: "This will overwrite 'answer.py' if you already have it downloaded. If you have started on the lab and want to save your work, rename your 'answer.py' to something else before continuing.\n Do you want to continue?"
    vars:
      LAB_PATH:
        sh: echo "$PWD" | awk -F'/src/' '{print $2}'
    cmds:
      - task: download-artifacts
      - cp -a {{.ARTIFACT_TMP_FILES}}/src/{{.LAB_PATH}}/. .
      - task: clear-artifacts
      - echo "{{.CLI_ARGS}} downloaded successfully. You can use the command 'ls' to se what files have been downloaded."



  download-workflow:
    desc: "Download workflows file that checks code at pull request."
    cmds:
      - mkdir -p .github/workflows
      - curl -s -L -o .github/workflows/main.yml {{.ARTIFACT_REPO_FILES}}/.github/workflows/main.yml
      - echo "Workflow file downloaded successfully."


  download-extensions:
    desc: "Download file with recommended extensions."
    cmds:
      - mkdir -p .vscode
      - curl -s -L -o .vscode/extensions.json {{.ARTIFACT_REPO_FILES}}/.vscode/extensions.json
      - curl -s -L -o .vscode/settings.json {{.ARTIFACT_REPO_FILES}}/.vscode/settings.json
      - echo "Recommended extensions successfully."



  check-have-files:
    desc: "Checks that repo contain all needed files."
    cmds:
      - | 
        [ -f .gitignore ] && echo "✅ .gitignore file found!" || { echo "❌ Error: .gitignore file not found!"; exit 1; }
        [ -f .github/workflows/main.yml ] && echo "✅ .github/workflows/main.yml file found!" || { echo "❌ Error: .github/workflows/main.yml file not found!"; exit 1; }
        [ -d tests ] && echo "✅ tests directory found!" || { echo "❌ Error: tests directory not found!"; exit 1; }
        [ -f .editorconfig ] && echo "✅ .editorconfig file found!" || { echo "❌ Error: .editorconfig file not found!"; exit 1; }
        [ -f .python-version ] && echo "✅ .python-version file found!" || { echo "❌ Error: .python-version file not found!"; exit 1; }
        [ -f pyproject.toml ] && echo "✅ pyproject.toml file found!" || { echo "❌ Error: pyproject.toml file not found!"; exit 1; }
        [ -f ruff.toml ] && echo "✅ ruff.toml file found!" || { echo "❌ Error: ruff.toml file not found!"; exit 1; }
        [ -f uv.lock ] && echo "✅ uv.lock file found!" || { echo "❌ Error: uv.lock file not found!"; exit 1; }


  # ==========================================
  # Testing Commands
  # ==========================================

  test:
    desc: "Run tests for a specific assignment. Usage: 'task test -- kmom01' or 'kmom01/convert' to run specific tests"
    cmds:
      - |
        echo "Run tests with the 'uv run tester' command. Use 'uv run tester -h' for more options."


  # # ==========================================
  # # Linting Commands  tror inte jag vill ha dessa i Taskfile, de kan köras direkt med uv run ruff check src/ eller liknande
  # # ==========================================

  # lint:
  #   desc: "Check code with Ruff linter (no fixes applied)"
  #   cmds:
  #     - echo "Running Ruff linter on src/..."
  #     - uv run ruff check src/



  # ==========================================
  # Branch Workflow Commands
  # ==========================================

  start-kmom:
    desc: "Start a new assignment by creating a branch. Usage: 'task start-kmom -- kmom02'"
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "❌ Error: Please specify an assignment. Usage: task start-kmom -- kmom02"
          exit 1
        fi
        KMOM="{{.CLI_ARGS}}"
        CURRENT_BRANCH=$(git branch --show-current)
        echo "Current branch: $CURRENT_BRANCH"
        
        # Extract kmom number
        KMOM_NUM=$(echo $KMOM | grep -o '[0-9]\+')
        
        # Determine source branch
        if [ "$KMOM_NUM" = "01" ]; then
          SOURCE_BRANCH="main"
        else
          PREV_NUM=$(printf "%02d" $((10#$KMOM_NUM - 1)))
          SOURCE_BRANCH="kmom$PREV_NUM"
        fi
        
        # Check if branch already exists
        if git show-ref --verify --quiet refs/heads/$KMOM; then
          echo "⚠️  Branch '$KMOM' already exists. Switching to it..."
          git checkout $KMOM
        else
          echo "Creating new branch '$KMOM' from '$SOURCE_BRANCH'..."
          git checkout -b $KMOM $SOURCE_BRANCH
          git push --set-upstream origin $KMOM
          echo "✅ Branch '$KMOM' created and checked out."

        fi
        echo ""
        echo "Next steps:"
        echo "  1. Create your implementation in src/$KMOM/"
        echo "  2. Run tests: task test -- $KMOM"
        echo "  3. Check linting: task lint"
        echo "  4. Commit and push your changes"

  switch-kmom:
    desc: "Switch to an assignment branch. Usage: 'task switch-kmom -- kmom01'"
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "❌ Error: Please specify an assignment. Usage: task switch-kmom -- kmom01"
          exit 1
        fi
        KMOM="{{.CLI_ARGS}}"
        if git show-ref --verify --quiet refs/heads/$KMOM; then
          echo "Switching to branch '$KMOM'..."
          git checkout $KMOM
        else
          echo "❌ Error: Branch '$KMOM' does not exist. Create it with: task start-kmom -- $KMOM"
          exit 1
        fi

  branches:
    desc: "List all assignment branches"
    cmds:
      - |
        echo "Assignment branches:"
        git branch | grep -E 'kmom[0-9]+' || echo "No assignment branches found."
        echo ""
        echo "Current branch: $(git branch --show-current)"


  # ==========================================
  # Submission Commands
  # ==========================================

  check-ready:
    desc: "Check if assignment is ready for submission. Usage: 'task check-ready -- kmom01'"
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "❌ Error: Please specify an assignment. Usage: task check-ready -- kmom01"
          exit 1
        fi
        KMOM="{{.CLI_ARGS}}"
        echo "Checking readiness for $KMOM..."
        echo ""
        
        # Check if on correct branch
        CURRENT_BRANCH=$(git branch --show-current)
        if [ "$CURRENT_BRANCH" != "$KMOM" ]; then
          echo "⚠️  Warning: You are on branch '$CURRENT_BRANCH', not '$KMOM'"
        else
          echo "✅ On correct branch: $KMOM"
        fi
        
        # Check for uncommitted changes
        if [ -n "$(git status --porcelain)" ]; then
          echo "⚠️  Warning: You have uncommitted changes"
          git status --short
        else
          echo "✅ No uncommitted changes"
        fi
        
        echo ""
        echo "Running structure tests..."
        if uv run tester tests/$KMOM/ -t struct; then
          echo "✅ Structure tests passed"
        else
          echo "❌ Structure tests failed"
          exit 1
        fi
        
        echo ""
        echo "Running all tests..."
        if uv run tester tests/$KMOM/; then
          echo "✅ All tests passed"
        else
          echo "❌ Some tests failed"
          exit 1
        fi
        
        echo ""
        echo "Checking code with Ruff..."
        if uv run ruff check src/$KMOM/; then
          echo "✅ Ruff checks passed"
        else
          echo "❌ Ruff found issues"
          exit 1
        fi
        
        echo ""
        echo "🎉 $KMOM is ready for submission!"

  tag-version:
    desc: "Create a version tag for assignment. Usage: 'task tag-version -- kmom01 1.0.0'"
    cmds:
      - |
        ARGS="{{.CLI_ARGS}}"
        if [ -z "$ARGS" ]; then
          echo "❌ Error: Please specify assignment and version. Usage: task tag-version -- kmom01 1.0.0"
          exit 1
        fi
        KMOM=$(echo $ARGS | awk '{print $1}')
        VERSION=$(echo $ARGS | awk '{print $2}')
        if [ -z "$VERSION" ]; then
          echo "❌ Error: Please specify a version. Usage: task tag-version -- kmom01 1.0.0"
          exit 1
        fi
        
        # Extract kmom number
        KMOM_NUM=$(echo $KMOM | grep -o '[0-9]\+')
        TAG="v${KMOM_NUM}.${VERSION}"
        
        echo "Creating tag '$TAG' for $KMOM..."
        git tag -a "$TAG" -m "Release $KMOM version $VERSION"
        echo "✅ Tag '$TAG' created."
        echo ""
        echo "To push the tag to remote, run:"
        echo "  git push origin $TAG"


  # ==========================================
  # Workflow Helper Commands
  # ==========================================

  status:
    desc: "Show current assignment status and context"
    cmds:
      - |
        echo "======================================"
        echo "Assignment Status"
        echo "======================================"
        echo ""
        CURRENT_BRANCH=$(git branch --show-current)
        echo "📍 Current branch: $CURRENT_BRANCH"
        
        # Check if on assignment branch
        if echo "$CURRENT_BRANCH" | grep -q "kmom"; then
          KMOM=$CURRENT_BRANCH
          echo "📝 Working on: $KMOM"
          
          # Check for src directory
          if [ -d "src/$KMOM" ]; then
            echo "📁 Source directory: src/$KMOM"
            FILE_COUNT=$(find src/$KMOM -name "*.py" -type f 2>/dev/null | wc -l)
            echo "   Python files: $FILE_COUNT"
          else
            echo "⚠️  Source directory src/$KMOM does not exist"
          fi
          
          # Check for uncommitted changes
          if [ -n "$(git status --porcelain)" ]; then
            echo "⚠️  Uncommitted changes present"
          else
            echo "✅ No uncommitted changes"
          fi
        else
          echo "ℹ️  Not on an assignment branch"
        fi
        
        echo ""
        echo "Available assignments:"
        git branch | grep -E 'kmom[0-9]+' | sed 's/^/  /' || echo "  No assignment branches found"
        
        echo ""
        echo "Next steps:"
        echo "  • Start new assignment: task start-kmom -- kmom0X"
        echo "  • Run tests: task test -- kmom0X"
        echo "  • Check linting: task lint"
        echo "  • Check readiness: task check-ready -- kmom0X"

  setup:
    desc: "Initial setup - run all configuration downloads"
    cmds:
      - echo "Running initial setup..."
      - task: create-src-dirs
      - task: download-tests
      - task: download-ruff-config
      - task: download-workflow
      - task: download-extensions
      - task: check-have-files
      - echo ""
      - echo "✅ Setup complete!"
      - echo ""
      - echo 'Next steps{{":"}}'
      - echo '  1. Start your first assignment{{":"}} task start-kmom -- kmom01'
      - echo '  2. Implement your code in src/kmom01/'
      - echo '  3. Run tests{{":"}} task test -- kmom01'

  help:
    desc: "Show detailed help for common workflow commands"
    cmds:
      - |
        echo "======================================"
        echo "Student Workflow Help"
        echo "======================================"
        echo ""
        echo "🚀 Getting Started:"
        echo "  task setup              - Initial setup (run once)"
        echo "  task start-kmom -- kmom01 - Start first assignment"
        echo ""
        echo "📝 Development:"
        echo "  task test -- kmom01     - Run tests for assignment"
        echo "  task test-struct -- kmom01 - Run only structure tests"
        echo "  task lint               - Check code quality"
        echo "  task format-check       - Check code formatting"
        echo ""
        echo "🔀 Branch Management:"
        echo "  task switch-kmom -- kmom01 - Switch to assignment branch"
        echo "  task branches           - List all assignment branches"
        echo "  task status             - Show current status"
        echo ""
        echo "✅ Submission:"
        echo "  task check-ready -- kmom01 - Verify assignment is ready"
        echo "  task tag-version -- kmom01 1.0.0 - Create version tag"
        echo ""
        echo "📥 Updates:"
        echo "  task download-tests     - Update test files"
        echo "  task download-ruff-config - Update linting config"
        echo ""
        echo "For more details, run: task --list"
